// Generated by https://quicktype.io
export interface QuestionType {
    id:   number;
    name: string;
}

export interface Question {
    id: number;
    content: string;
    answers?: Answer[];
}

export interface Answer {
    id: number;
    content: string;
}